### ISSUE TITLE
keepers.png lost from repo - readme doesn't show image.

### ISSUE THREAD

**Issue by ChefAharoni** [Cyfrin/foundry-smart-contract-lottery-f23#14]
The image of _keepers.png_ has probably moved/deleted/corrupted, and the link in the readme looks corrupted as seen below:
<img width="898" alt="image" src="https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/assets/4399057/966ee1e0-6d49-4eb9-a86c-f929e9ed695f">
<br>
When following the link, GitHub says the file no longer exists:
<img width="1395" alt="image" src="https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/assets/4399057/2894c9e7-ae91-4948-8e3a-321bcb95e4fb">

**Comment by PatrickAlphaC** [comment]
Fixed here! Thanks.

https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/commit/f5d01aaa3f861960f25f8a8a3b85cc293c1c7c86
