### ISSUE TITLE
 ERROR forge::runner: setUp failed reason="ERC20: transfer amount exceeds balance"

### ISSUE THREAD

**Issue by blagoichelovek** [Cyfrin/foundry-smart-contract-lottery-f23#19]
After compile with forge test --fork-url $SEPOLIA_RPC_URL --via-ir it throws me wierd error:
Running 1 test for test/unit/RaffleTest.t.sol:RaffleTest
[FAIL. Reason: Setup failed: ERC20: transfer amount exceeds balance] setUp() (gas: 0)
Test result: FAILED. 0 passed; 1 failed; finished in 9.33s

Failing tests:
Encountered 1 failing test in test/unit/RaffleTest.t.sol:RaffleTest
[FAIL. Reason: Setup failed: ERC20: transfer amount exceeds balance] setUp() (gas: 0)

**Comment by ungureanuu** [comment]
try to add more SepoliaETH (https://sepoliafaucet.com/) to the account that you have the privite key inside .env

**Comment by howellsy** [comment]
Along the same lines, I had to add some more LINK (https://faucets.chain.link/) to my account from `.env` to fix this error.

**Comment by PatrickAlphaC** [comment]
Nice, great fixes all
