### ISSUE TITLE
No need for vm.roll() after vm.warp()!!

### ISSUE THREAD

**Issue by ShivamDeshmukh21** [Cyfrin/foundry-smart-contract-lottery-f23#21]
@PatrickAlphaC always writes vm.warp() and vm.roll() one after the other which might give off the impression that one is dependent on the other BUT that's not true; warp() is used to set a custom block timestamp (needed to check if enough time has passed since the start of the raffle), whereas roll() is used to set the block number which we don't need at all!

**Comment by moayaan1911** [comment]
![Screenshot 2023-11-10 233330](https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/assets/95223782/6483aa4c-cf14-4fa5-9fde-e41c5d772e31)
Getting this error. EVM revert, I have entered subscription id manually from UI

**Comment by crunter** [comment]
actually, Patrick Says explicitly that it is not needed (05:14:02), but it is recommended!!

**Comment by PatrickAlphaC** [comment]
@crunter got it!
