### ISSUE TITLE
Error with file path when importing forge-std/Script.sol

### ISSUE THREAD

**Issue by HussamX98** [Cyfrin/foundry-smart-contract-lottery-f23#23]
I was following along and I'm having issues with the file paths when importing. I'm getting this error: "Source "forge-std/Script.sol" not found: File import callback not supported that this file path doesn't exist".
I tried remapping but it didn't work. What are some suggestions I can try? Thanks!

**Comment by MGM103** [comment]
Hi Hussam, I followed the advice in the following stack exchange post: https://ethereum.stackexchange.com/questions/142459/forge-std-test-sol-imported-and-working-but-vscode-marks-an-error

I modified my settings.json as specified in the second highest answer and that did the trick for.

**Comment by PatrickAlphaC** [comment]
Closing due to stale
