### ISSUE TITLE
A test assignmnet improvement.

### ISSUE THREAD

**Issue by DevSwayam** [Cyfrin/foundry-smart-contract-lottery-f23#32]
## Description
Sir at this timestamp https://youtu.be/sas02qSFZ74?t=21550 you said that you can cross check the test you have written by referring github repo and currently the answer is not available, can i make a PR for it?

![image](https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/assets/99035115/98b3c11f-01df-4955-9767-a0312dd7eab5)

**Comment by PatrickAlphaC** [comment]
Thanks! You can... But I won't accept it :)
