### ISSUE TITLE
EVM revert performUpkeep

### ISSUE THREAD

**Issue by moayaan1911** [Cyfrin/foundry-smart-contract-lottery-f23#38]
![Screenshot 2023-11-10 233330](https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/assets/95223782/3941d712-e6e9-4f01-b63e-5306b06acd6e)
Getting this error again and again. Its showing EVM revert.

**Comment by ElahiAli** [comment]
Could you please try using ```performUpKeep("")``` instead of ```performUpKeep(0x)```?

**Comment by moayaan1911** [comment]
> Could you please try using `performUpKeep("")` instead of `performUpKeep(0x)`?

https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/issues/38#issuecomment-1834136062

**Comment by FilipAndonov** [comment]
I have the same problem and still can't figure it out why. If someone has fixed it can you please tell the solution?

**Comment by PatrickAlphaC** [comment]
Could you try to clone the repo, run the tests, and see if you still get the same error?
