### ISSUE TITLE
ERROR: Member "keyExists" not found (Foundry DevOpsTools error) 

### ISSUE THREAD

**Issue by Mitochondria99** [Cyfrin/foundry-smart-contract-lottery-f23#41]
I'm writing a smart contract lottery code, and after adding a consumer script and doing a forge build, I received this error. 

<img width="664" alt="ERROR" src="https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/assets/20863263/6ef5946b-c283-4683-bfbb-1dafeed766dc">

**Comment by PatrickAlphaC** [comment]
Could you update foundry with `foundryup`?

**Comment by PatrickAlphaC** [comment]
Closing due to stale
