### ISSUE TITLE
Subscription ID too large?

### ISSUE THREAD

**Issue by MorningLit** [Cyfrin/foundry-smart-contract-lottery-f23#48]
![image](https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/assets/57279935/1355f0d8-221f-4972-9533-9b88e5ce0ca7)
Currently following part 24 of the lottery smart contract series, and can't seem to fit my subscription id into uint64
https://www.youtube.com/watch?v=DgPYEyiE8NQ&list=PL2-Nvp2Kn0FPH2xU3IbKrrkae-VVXs1vk&index=132

**Comment by MorningLit** [comment]
My subscription id is 
58702003961984393061086325485375073005356194632241668487883182282754836008638
on the sepolia chain

**Comment by PatrickAlphaC** [comment]
Can you create a screenshot of how you got that number? That' _shouldn't_ be possible for your id to be that large.

**Comment by MorningLit** [comment]
![image](https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/assets/57279935/bd3277e3-c96a-4946-8ffd-011ee6287320)
I clicked on the clipboard icon on id and it also shows up in the URL

I've checked your video and it also looks to be that way I think
![image](https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/assets/57279935/239956c9-951b-47f3-9c35-8caa47a7a58d)

And thanks for replying so quickly Patrick!

**Comment by MorningLit** [comment]
Managed to solve this by programmatically running the CreateSubscription script Patrick created in this video 
https://www.youtube.com/watch?v=oLvQR5FNCu0&list=PL2-Nvp2Kn0FPH2xU3IbKrrkae-VVXs1vk&index=128

Not sure why trying to create a subscription in the UI would result in a very long ID 🤔 
eg: https://vrf.chain.link/sepolia/29705503198910972370636457615343113706079550398650684013578130209810340992079 
https://vrf.chain.link/sepolia/58702003961984393061086325485375073005356194632241668487883182282754836008638

**Comment by MorningLit** [comment]
Oh, found out the reason why there is the very large integer, it's because in version 2.5 of chainlink VRF, they increased the size from uint64 to uint256
Related docs here: https://docs.chain.link/vrf/v2-5/migration-from-v2

**Comment by PatrickAlphaC** [comment]
I see... Thanks for this!

**Comment by cromewar** [comment]
The update was referred directly on the code: https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/blob/d106fe245e0e44239dae2479b63545351ed1236a/src/Raffle.sol#L54

We also added a note on the written lesson on Updraft stating this update. Thanks a lot, @MorningLit and @PatrickAlphaC
