### ISSUE TITLE
VRF v2.5 update doesn't integrate with contract

### ISSUE THREAD

**Issue by NerfZeri** [Cyfrin/foundry-smart-contract-lottery-f23#50]
as the 29th of April, with the release of the new VRF v2.5 subscription takes a much larger number for the subscription ID so will not work with the fork test contract.

all the subscription ID uints need to be updated to a uint256 and a new VRF aggregator contract needs to be imported for the fork test to work.

alternatively a v2 subscription can be launched by code,

both seem quite daunting so once i'm further along with my journey id love to come back and give it a go!

**Comment by PatrickAlphaC** [comment]
Thank you. We might have to do a bigger update to all the examples...

**Comment by PatrickAlphaC** [comment]
https://github.com/Cyfrin/foundry-smart-contract-lottery-f23/blob/0f1efe8b9c09aff57c58e0252152559c15064abb/src/Raffle.sol#L54

We've updated a comment in the github, and added an `update` section in Updraft.

Might need to refilm this at some point.

**Comment by PatrickAlphaC** [comment]
Closing for now.
