### ISSUE TITLE
my vs code solidity compiler version is not able to update or change 

### ISSUE THREAD

**Issue by harpreettrader** [Cyfrin/foundry-smart-contract-lottery-f23#8]
```solidity 
pragma solidity ^0.8.13; 
```

shows red line when is write this code and give me the error like 

Source file requires different compiler version (current compiler is 0.5.11+commit.c082d0b4.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version

**Comment by Ritik-Agarwal50** [comment]
Can You push your code into Github So I can have look into it.
